@startuml
'https://plantuml.com/class-diagram

package "domain.repository" {

    interface ChatRepository {
        + getMessages(): Flow<List<ChatMessage>>
        + sendMessage(text: String): Result<Unit>
    }

    interface OccupancyRepository{
        + getPredictedOccupancy(parkingAreaId): Result<Int>
    }

    interface AlertRepository {
        + getAlertsByAccountId(accountId: String): Result<List<Alert>>
        + markAsRead(alertId: String): Result<Unit>
        + markAllAsRead(accountId: String): Result<Unit>
    }

    interface AuthRepository {
        + getAuthStateFlow(): Flow<AuthState>
        + getCurrentUserId(): Result<String>
        + login(email: String, pass: String): Result<String>
        + signout(): Result<Unit>
        + register(email: String, password: String): Result<String>
        + requestPasswordReset(email: String): Result<Unit>
    }

    interface AccountRepository {
        + getAccount(userId: String): Result<Account>
        + createAccount(userId: String, name: String, taxId: String, role: Role): Result<Account>
        + saveLocally(account: Account)
        + getCachedAccount(): Account?
        + clearAccount()
        + updatePoints(accountId: String, points: Int): Result<Unit>
    }

    interface LocationRepository {
        + getUserLocation(): UserLocation
    }

    interface ParkingAreaRepository {
        + getParkingAreaById(parkingAreaId: String): Result<ParkingArea>
        + getParkingAreasByOwner(ownerId: String): Result<List<ParkingArea>>
        + getNearbyParkingAreas(lat: Double, lon: Double, dist: Double): Result<List<ParkingArea>>
        + addParkingArea(parkingArea: ParkingArea): Result<Unit>
        + updateParkingArea(parkingArea: ParkingArea): Result<Unit>
        + deactivateParkingArea(parkingAreaId: String): Result<Unit>
        + toggleOperativeState(parkingAreaId: String, isOperative: Boolean): Result<Unit>
    }

    interface ReservationRepository {
        + findById(reservationId: String): Result<Reservation>
        + findByAccountId(accountId: String): Result<List<Reservation>>
        + findByParkingId(parkingAreaId: String): Result<List<Reservation>>
        + findActiveReservationByAccountId(accountId: String): Result<List<Reservation>>
        + findActiveReservationByParkingId(parkingAreaId: String): Result<List<Reservation>>
        + save(reservation: Reservation): Result<Unit>
        + updateState(reservationId: String, newState: ReservationState): Result<Unit>
        + extend(reservationId: String, newOutTime: Instant): Result<Unit>
        + countParkingActiveReservations(parkingAreaId: String): Int
        + countUserActiveReservations(accountId: String): Int
        + countCompletedReservationsByUserInParking(accountId: String, parkingAreaId: String): Result<Int>
    }

    interface EcoMetricsRepository {
        + getUserEcoMetrics(accountId: String): Result<UserEcoMetrics>
        + getAdminEcoMetrics(): Result<AdminEcoMetrics>
    }

    interface ThemeRepository {
        + getThemes(): Result<List<Theme>>
        + getUserThemes(accountId: String): Result<List<Theme>>
        + unlockTheme(accountId: String, themeId: String): Result<Unit>
        + applyTheme(accountId: String, themeId: String): Result<Unit>
    }
}

package "data.repository" {

    class SupabaseChatRepository {
        - client: SupabaseClient
        + getMessages(): Flow<List<ChatMessage>>
        + sendMessage(text: String): Result<Unit>
    }

    class SupabaseAuthRepository {
        - client: SupabaseClient
    }

    class SupabaseAccountRepository {
        - client: SupabaseClient
        - localDataSource: AccountLocalDataSource
    }

    class CompassLocationRepository {
        - geolocator: Geolocator
    }

    class SupabaseParkingAreaRepository {
        - client: SupabaseClient
    }

    class SupabaseReservationRepository {
        - client: SupabaseClient
    }

    class AnalyticsOccupancyRepository{
        - httpClient: HttpClient
        - supabaseClient: SupabaseClient
    }

    class SupabaseAlertRepository {
        - client: SupabaseClient
    }

    class SupabaseEcoMetricsRepository {
        - client: SupabaseClient
    }

    class SupabaseThemeRepository {
        - client: SupabaseClient
    }

    ' Implementaciones
    SupabaseAuthRepository .up.|> AuthRepository
    SupabaseAccountRepository .up.|> AccountRepository
    CompassLocationRepository .up.|> LocationRepository
    SupabaseParkingAreaRepository .up.|> ParkingAreaRepository
    SupabaseReservationRepository .up.|> ReservationRepository
    AnalyticsOccupancyRepository .|> OccupancyRepository
    SupabaseAlertRepository .up.|> AlertRepository
    SupabaseEcoMetricsRepository .up.|> EcoMetricsRepository
    SupabaseThemeRepository .up.|> ThemeRepository
}

package "data.local"{
    class AccountLocalDataSource <<LocalData>>
    class ThemeLocalDataSource <<LocalData>>
}

' Dependencias externas representadas simplificadamente
class SupabaseClient <<External>>
class Geolocator <<External>>

SupabaseAuthRepository --> SupabaseClient
SupabaseAccountRepository --> SupabaseClient
SupabaseAccountRepository --> AccountLocalDataSource
SupabaseParkingAreaRepository --> SupabaseClient
SupabaseReservationRepository --> SupabaseClient
CompassLocationRepository --> Geolocator
AnalyticsOccupancyRepository --> SupabaseClient
SupabaseAlertRepository --> SupabaseClient
SupabaseEcoMetricsRepository --> SupabaseClient
SupabaseThemeRepository --> SupabaseClient
SupabaseChatRepository .up.|> ChatRepository
SupabaseChatRepository --> SupabaseClient

@enduml
